services:
  history-user-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: history-user-master
    restart: unless-stopped
    ports:
      - "3014:3000"
    networks:
      - history-user-master-network

networks:
  history-user-master-network:
    driver: bridge
